### PR TITLE
Hide mainWindow while performing actions

### PR DESCRIPTION
**Pull request by andrewschreiber**
### Changes
- Refactors window logic into a window.ts file
- Adds simple hide/show behavior to make sure the window does not interfere with screenshots or clicking

Fixes errors discussed here 

https://news.ycombinator.com/item?id=41926770

### CODE REVIEW

**Comment by corbt** [comment]
Nice! Can you share a screen recording of the new behavior?

**Comment by andrewschreiber** [comment]
attached

**Comment by andrewschreiber** [comment]
https://github.com/user-attachments/assets/ae8e706e-3e28-4d82-b622-b71b6084f787

**Comment by corbt** [comment]
I agree this fix is helpful but I worry it's going to make the app feel super glitchy (the disappearing/reappearing feels like a bug, even though it's intentional).

**Comment by genecyber** [comment]
you *could* make it a transparency and have it be a setting, so on screenshot it makes the window transparent (add an step loop to make it not feel glitchy) if a user wants, they can choose 0 transparency

**Comment by andrewschreiber** [comment]
Added a fade.

Could imagine many more improvements to this UX, but don't have time currently. Feel free to tweak the values if desired

https://github.com/user-attachments/assets/ce7a9832-bc2a-41df-8624-b998c1e7ccac

**Comment by corbt** [comment]
Ok, this looks good! Agreed there are better ways to handle this but this is a nice short-term improvement. 🙂

**Comment by huyquocaimesoft** [comment]
Sorry, after pull new code version, I found error:
`Cannot read properties of undefined (reading 'length')`
Relative to line 168 at App.tsx `{!running && runHistory.length > 0 && (`

How can I solve it. Thank you.

**Pull request merged**
